import SwiftUI
import SwiftData
import TabletomeHobbyData
import TabletomeDomain

struct NewRosterSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var context
    @Environment(AppRouter.self) private var router
    @Query(sort: \Army.sortIndex) private var armies: [Army]
    @Query private var configs: [AppConfiguration]

    var prefillGame: String?
    var prefillFaction: String?
    var prefillLinkedArmyId: UUID?

    @State private var game = "40k"
    @State private var faction = ""
    @State private var battleSizeKey = "strike-force"
    @State private var customPointsText = "750"
    @State private var name = ""
    @State private var lastAutoGeneratedName = ""
    @State private var linkedArmyId: UUID?
    @State private var errorMessage: String?
    @State private var showsStarterBoxBanner = true
    @FocusState private var focusedField: Field?

    private enum Field: Hashable {
        case customPoints
    }

    private var hasExplicitPrefill: Bool {
        prefillFaction != nil || prefillLinkedArmyId != nil
    }

    private var sessionPrefill: NewRosterPrefillResolver.Prefill? {
        NewRosterPrefillResolver.prefill(
            onboardingChoice: FirstSessionStore.onboardingChoice,
            activeGameSystemId: router.activeGameSystemId,
            hasExplicitPrefill: hasExplicitPrefill
        )
    }

    private var starterBoxGuidance: NewRosterPrefillResolver.StarterBoxGuidance? {
        showsStarterBoxBanner ? sessionPrefill?.starterBoxGuidance : nil
    }

    private var factions: [String] { FactionResolver.canonicalByGame[game]?.sorted() ?? [] }
    private var suggestedFactions: [String] {
        let suggested = sessionPrefill?.suggestedFactions ?? []
        return suggested.filter { factions.contains($0) }
    }
    private var otherFactions: [String] {
        factions.filter { !suggestedFactions.contains($0) }
    }
    private var battleSizes: [BattleSize] { BattleSizes.forGame(game) }
    private var matchingArmies: [Army] {
        armies.filter {
            $0.game == game && FactionResolver.normalize($0.faction) == FactionResolver.normalize(resolvedFaction)
        }
    }
    private var resolvedFaction: String { faction.isEmpty ? (factions.first ?? "Custom") : faction }
    private var parsedCustomPoints: Int? {
        Int(customPointsText.trimmingCharacters(in: .whitespaces))
    }
    private var canCreate: Bool {
        !name.trimmingCharacters(in: .whitespaces).isEmpty
            && !faction.isEmpty
            && isBattleSizeValid
    }
    private var isBattleSizeValid: Bool {
        battleSizeKey != BattleSizes.customKey || (parsedCustomPoints ?? 0) > 0
    }
    private var recommendedBattleSizeKey: String {
        configs.first?.defaultBattleSizeKey40k ?? "strike-force"
    }
    private var playGameSystemId: String {
        FirstSessionStore.onboardingChoice
            ?? router.activeGameSystemId
    }

    private var resolvedPlayGameSystemId: String {
        let candidate = playGameSystemId
        if GameSystemId(knownRawValue: candidate) != nil { return candidate }
        return OnboardingCompletion.defaultGameSystemId
    }

    private var showsNon40kListsNote: Bool {
        !is40kGameSystem(resolvedPlayGameSystemId)
    }

    private var customPointsValidationMessage: String? {
        guard battleSizeKey == BattleSizes.customKey else { return nil }
        let trimmed = customPointsText.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return nil }
        guard let points = parsedCustomPoints, points > 0 else {
            return String(localized: "Enter a point limit greater than zero.")
        }
        return nil
    }

    private func is40kGameSystem(_ gameSystemId: String) -> Bool {
        guard let gameSystem = GameSystemId(knownRawValue: gameSystemId) else { return false }
        return gameSystem == .wh40k11e || gameSystem == .wh40k10eCp
    }

    var body: some View {
        NavigationStack {
            Form {
                if let starterBoxGuidance {
                    Section {
                        NewRosterStarterBoxBanner(
                            guidance: starterBoxGuidance,
                            onOpenGuidedMatch: openGuidedMatch,
                            onDismiss: { showsStarterBoxBanner = false }
                        )
                        .listHeroCardRow()
                    }
                }

                Section {
                    HStack(spacing: 10) {
                        Image(systemName: HobbyGameSymbol.systemImage(for: game))
                            .font(.title3)
                            .foregroundStyle(Color.accentOnSurface)
                            .symbolRenderingMode(.hierarchical)
                            .frame(width: 28)
                            .accessibilityHidden(true)
                        Text(String(localized: "Warhammer 40,000"))
                            .font(.body.weight(.medium))
                    }

                    Picker(String(localized: "Faction"), selection: $faction) {
                        Text(String(localized: "Choose…")).tag("")
                        ForEach(suggestedFactions + otherFactions, id: \.self) { f in
                            HStack(spacing: 8) {
                                Circle()
                                    .fill(Color(hex: FactionResolver.resolve(faction: f, game: game, overrides: []).colorHex))
                                    .frame(width: 8, height: 8)
                                    .accessibilityHidden(true)
                                Text(f)
                            }
                            .tag(f)
                        }
                    }
                    .formNavigationPickerStyle()
                    .onChange(of: faction) { _, _ in updateDefaultName() }

                    if !faction.isEmpty {
                        let pres = FactionResolver.resolve(faction: resolvedFaction, game: game, overrides: [])
                        HStack(spacing: 12) {
                            CrestBadge(
                                text: pres.crest,
                                colorHex: pres.colorHex,
                                imageFileName: pres.imageFileName
                            )
                            VStack(alignment: .leading, spacing: 2) {
                                Text(String(localized: "Preview"))
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                                Text(resolvedFaction)
                                    .font(.subheadline.weight(.medium))
                            }
                            Spacer(minLength: 0)
                        }
                        .padding(.vertical, 4)
                    }
                } header: {
                    Text(String(localized: "Game & faction"))
                } footer: {
                    if showsNon40kListsNote, faction.isEmpty, errorMessage == nil {
                        Text(non40kListsNote)
                    } else if faction.isEmpty, errorMessage == nil {
                        Text(
                            String(
                                localized: "Pick the army you're building toward — you can change this later."
                            )
                        )
                    }
                }

                Section {
                    Picker(String(localized: "Battle size"), selection: $battleSizeKey) {
                        ForEach(battleSizes) { size in
                            battleSizeLabel(size).tag(size.id)
                        }
                        Text(String(localized: "Custom…")).tag(BattleSizes.customKey)
                    }
                    .formNavigationPickerStyle()

                    if battleSizeKey == BattleSizes.customKey {
                        TextField(String(localized: "Point limit"), text: $customPointsText)
                            .keyboardType(.numberPad)
                            .focused($focusedField, equals: .customPoints)
                            .accessibilityIdentifier("musterNewRoster.customPoints")
                    }

                    TextField(String(localized: "List name"), text: $name)
                        .textInputAutocapitalization(.words)
                } header: {
                    Text(String(localized: "List"))
                } footer: {
                    NewRosterListSectionFooter(
                        errorMessage: errorMessage,
                        customPointsValidationMessage: customPointsValidationMessage,
                        battleSizeHint: battleSizeHint,
                        skipToPlayLabel: skipToPlayLabel,
                        skipToPlayAccessibilityHint: skipToPlayAccessibilityHint,
                        onSkipToPlay: skipToPlay
                    )
                }

                if !faction.isEmpty {
                    Section {
                        if !matchingArmies.isEmpty {
                            Picker(String(localized: "Collection army"), selection: $linkedArmyId) {
                                Text(String(localized: "None")).tag(UUID?.none)
                                ForEach(matchingArmies) { army in
                                    NewRosterArmyRow(
                                        army: army,
                                        overrides: configs.first?.factionOverrides ?? []
                                    )
                                    .tag(Optional(army.id))
                                }
                            }
                            .formNavigationPickerStyle()
                        }
                    } header: {
                        Text(String(localized: "Collection link"))
                    } footer: {
                        if matchingArmies.isEmpty {
                            Text(
                                String(
                                    localized: """
                                    Track models under Models first, then link them here to see which units you can field.
                                    """
                                )
                            )
                        } else {
                            Text(FormHints.rosterLink)
                        }
                    }
                }
            }
            .scrollDismissesKeyboard(.interactively)
            .navigationTitle(String(localized: "New list"))
            .navigationBarTitleDisplayMode(.inline)
            .tabBarScrollInset()
            .readableContentWidth()
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(String(localized: "Cancel")) { dismiss() }
                        .accessibilityIdentifier("musterNewRoster.cancel")
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button(String(localized: "Create")) { createRoster() }
                        .accessibilityIdentifier("musterNewRoster")
                        .accessibilityLabel(String(localized: "Create list"))
                        .accessibilityHint(String(localized: "Saves this army list and opens the editor."))
                        .disabled(!canCreate)
                }
                ToolbarItemGroup(placement: .keyboard) {
                    Spacer()
                    Button(String(localized: "Done")) { focusedField = nil }
                }
            }
            .onAppear(perform: applyInitialValues)
        }
    }

    private var skipToPlayLabel: String {
        if NewRosterPrefillResolver.isFixedRosterGameSystem(resolvedPlayGameSystemId) {
            return String(localized: "Skip for now — open Guided Match")
        }
        return String(localized: "Skip for now — go to Play")
    }

    private var skipToPlayAccessibilityHint: String {
        if NewRosterPrefillResolver.isFixedRosterGameSystem(resolvedPlayGameSystemId) {
            return String(localized: "Closes this sheet and opens Guided Match on the Play tab.")
        }
        return String(localized: "Closes this sheet and opens your game guide on the Play tab.")
    }

    private var non40kListsNote: String {
        let playName = GameSystemRulesLabels.displayName(gameSystemId: resolvedPlayGameSystemId)
        return String(
            localized: """
            Army lists here are for Warhammer 40,000 point-building. For \(playName), use Play → Guided Match.
            """
        )
    }

    private var battleSizeHint: String {
        switch battleSizeKey {
        case "combat-patrol":
            return String(
                localized: """
                Combat Patrol (500 pts) is for planning small collections. GW's Combat Patrol format uses the fixed \
                units in your box — see Play for Guided Match.
                """
            )
        case BattleSizes.customKey:
            return String(
                localized: "Set the point limit your group agreed on. Strike Force (2,000 pts) is the usual pick for casual games."
            )
        default:
            if battleSizeKey == recommendedBattleSizeKey {
                return String(
                    localized: "Battle size sets the point limit — Strike Force (2,000 pts) is the usual pick for casual games."
                )
            }
            return String(
                localized: "Battle size sets the point limit for this list."
            )
        }
    }

    private func battleSizeLabel(_ size: BattleSize) -> Text {
        let suffix = size.id == recommendedBattleSizeKey
            ? String(localized: " — Most common")
            : ""
        return Text(String(localized: "\(size.label) (\(size.pointsLimit) pts)\(suffix)"))
    }

    private func applyInitialValues() {
        if let prefillGame { game = prefillGame }
        if let prefillFaction {
            faction = prefillFaction
        } else if faction.isEmpty, let suggested = sessionPrefill?.suggestedFactions.first {
            faction = suggested
        }
        if let prefillLinkedArmyId { linkedArmyId = prefillLinkedArmyId }
        if let suggestedSize = sessionPrefill?.suggestedBattleSizeKey, prefillFaction == nil {
            battleSizeKey = suggestedSize
        } else {
            battleSizeKey = configs.first?.defaultBattleSizeKey40k ?? battleSizeKey
        }
        updateDefaultName()
    }

    private func updateDefaultName() {
        let generated = defaultRosterName()
        if name.isEmpty || name == lastAutoGeneratedName {
            name = generated
            lastAutoGeneratedName = generated
        }
    }

    private func defaultRosterName() -> String {
        guard !faction.isEmpty else { return "" }
        return String(localized: "\(faction) Army")
    }

    private func openGuidedMatch(gameSystemId: String) {
        dismiss()
        router.openGuidedMatch(
            gameSystemId: gameSystemId,
            opensBattleTab: PlayContinuationResolver.shouldOpenBattleTab(gameSystemId: gameSystemId)
        )
    }

    private func skipToPlay() {
        let gameSystemId = resolvedPlayGameSystemId
        dismiss()
        if NewRosterPrefillResolver.isFixedRosterGameSystem(gameSystemId) {
            router.openGuidedMatch(
                gameSystemId: gameSystemId,
                opensBattleTab: PlayContinuationResolver.shouldOpenBattleTab(gameSystemId: gameSystemId)
            )
        } else {
            router.openGameGuide(gameSystemId: gameSystemId)
        }
    }

    private func createRoster() {
        do {
            let roster = try RosterStore.addRoster(
                name: name,
                game: game,
                faction: resolvedFaction,
                battleSizeKey: BattleSizes.storageKey(
                    selectionKey: battleSizeKey,
                    customPoints: parsedCustomPoints
                ),
                linkedArmyId: linkedArmyId,
                in: context
            )
            dismiss()
            router.openMuster(rosterId: roster.id)
        } catch RosterError.nameTaken {
            errorMessage = String(localized: "That list name is already taken.")
        } catch RosterError.rosterLimit {
            errorMessage = String(localized: "Maximum number of lists reached.")
        } catch {
            errorMessage = String(localized: "Could not create list.")
        }
    }
}
