import SwiftUI
import SwiftData
import TabletomeHobbyData
import TabletomeDomain

struct NewRosterSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var context
    @Environment(AppRouter.self) private var router
    @Query(sort: \Army.sortIndex) private var armies: [Army]
    @Query private var configs: [AppConfiguration]

    var prefillGame: String?
    var prefillFaction: String?
    var prefillLinkedArmyId: UUID?

    @State private var game = "40k"
    @State private var faction = ""
    @State private var battleSizeKey = "strike-force"
    @State private var customPointsText = "750"
    @State private var name = ""
    @State private var lastAutoGeneratedName = ""
    @State private var linkedArmyId: UUID?
    @State private var errorMessage: String?

    private var factions: [String] { FactionResolver.canonicalByGame[game]?.sorted() ?? [] }
    private var battleSizes: [BattleSize] { BattleSizes.forGame(game) }
    private var matchingArmies: [Army] {
        armies.filter {
            $0.game == game && FactionResolver.normalize($0.faction) == FactionResolver.normalize(resolvedFaction)
        }
    }
    private var resolvedFaction: String { faction.isEmpty ? (factions.first ?? "Custom") : faction }
    private var parsedCustomPoints: Int? {
        Int(customPointsText.trimmingCharacters(in: .whitespaces))
    }
    private var canCreate: Bool {
        !name.trimmingCharacters(in: .whitespaces).isEmpty
            && !faction.isEmpty
            && isBattleSizeValid
    }
    private var isBattleSizeValid: Bool {
        battleSizeKey != BattleSizes.customKey || (parsedCustomPoints ?? 0) > 0
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    Picker(String(localized: "Game"), selection: $game) {
                        Text(String(localized: "Warhammer 40,000")).tag("40k")
                    }
                    .formNavigationPickerStyle()
                    .onChange(of: game) { _, _ in
                        faction = ""
                        updateDefaultName()
                    }

                    Picker(String(localized: "Faction"), selection: $faction) {
                        Text(String(localized: "Choose…")).tag("")
                        ForEach(factions, id: \.self) { Text($0).tag($0) }
                    }
                    .formNavigationPickerStyle()
                    .onChange(of: faction) { _, _ in updateDefaultName() }
                } header: {
                    Text(String(localized: "Game & faction"))
                }

                Section {
                    Picker(String(localized: "Battle size"), selection: $battleSizeKey) {
                        ForEach(battleSizes) { size in
                            Text(String(localized: "\(size.label) (\(size.pointsLimit) pts)")).tag(size.id)
                        }
                        Text(String(localized: "Custom…")).tag(BattleSizes.customKey)
                    }
                    .formNavigationPickerStyle()

                    if battleSizeKey == BattleSizes.customKey {
                        TextField(String(localized: "Point limit"), text: $customPointsText)
                            .keyboardType(.numberPad)
                            .accessibilityIdentifier("musterNewRoster.customPoints")
                    }

                    TextField(String(localized: "List name"), text: $name)
                        .textInputAutocapitalization(.words)
                } header: {
                    Text(String(localized: "List"))
                } footer: {
                    if let errorMessage {
                        FormValidationFooter(message: errorMessage)
                    } else {
                        VStack(alignment: .leading, spacing: DesignTokens.Spacing.xs) {
                            Text(FormHints.uniqueName)
                            Text(
                                String(
                                    localized: "Battle size sets the point limit — Strike Force (2,000 pts) is the usual pick for casual games."
                                )
                            )
                        }
                    }
                }

                if !matchingArmies.isEmpty {
                    Section {
                        Picker(String(localized: "Collection army"), selection: $linkedArmyId) {
                            Text(String(localized: "None")).tag(UUID?.none)
                            ForEach(matchingArmies) { army in
                                Text(army.name).tag(Optional(army.id))
                            }
                        }
                        .formNavigationPickerStyle()
                    } header: {
                        Text(String(localized: "Collection link"))
                    } footer: {
                        Text(FormHints.rosterLink)
                    }
                }
            }
            .navigationTitle(String(localized: "New list"))
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(String(localized: "Cancel")) { dismiss() }
                        .accessibilityIdentifier("musterNewRoster.cancel")
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button(String(localized: "Create")) { createRoster() }
                        .accessibilityIdentifier("musterNewRoster")
                        .accessibilityLabel(String(localized: "Create list"))
                        .accessibilityHint(String(localized: "Saves this army list and opens the editor."))
                        .disabled(!canCreate)
                }
            }
            .onAppear {
                if let prefillGame { game = prefillGame }
                if let prefillFaction { faction = prefillFaction }
                if let prefillLinkedArmyId { linkedArmyId = prefillLinkedArmyId }
                if battleSizeKey.isEmpty {
                    battleSizeKey = configs.first?.defaultBattleSizeKey40k ?? "strike-force"
                }
                updateDefaultName()
            }
        }
    }

    private func updateDefaultName() {
        let generated = defaultRosterName()
        if name.isEmpty || name == lastAutoGeneratedName {
            name = generated
            lastAutoGeneratedName = generated
        }
    }

    private func defaultRosterName() -> String {
        guard !faction.isEmpty else { return "" }
        return String(localized: "\(faction) Army")
    }

    private func createRoster() {
        do {
            let roster = try RosterStore.addRoster(
                name: name,
                game: game,
                faction: resolvedFaction,
                battleSizeKey: BattleSizes.storageKey(
                    selectionKey: battleSizeKey,
                    customPoints: parsedCustomPoints
                ),
                linkedArmyId: linkedArmyId,
                in: context
            )
            dismiss()
            router.openMuster(rosterId: roster.id)
        } catch RosterError.nameTaken {
            errorMessage = String(localized: "That list name is already taken.")
        } catch RosterError.rosterLimit {
            errorMessage = String(localized: "Maximum number of lists reached.")
        } catch {
            errorMessage = String(localized: "Could not create list.")
        }
    }
}
